### ISSUE TITLE
Error "Cannot read properties of undefined (reading 'then')" on new conversation.

### ISSUE THREAD

**Issue by EdZava** [twilio/twilio-conversations-demo-react#118]
I downloaded the project and it runs correctly.
But when trying to create a new conversation it gives this error in the api.
I didn't see how to fix it.

This is the error:
<img width="975" alt="image" src="https://github.com/twilio/twilio-conversations-demo-react/assets/1155199/03259994-e7e9-49ed-86d9-36c526f86b5d">

I think the error is in this method:
<img width="856" alt="image" src="https://github.com/twilio/twilio-conversations-demo-react/assets/1155199/2f34c62d-5e06-4f75-a7e4-819fdb2cd5a9">

**Comment by berkus** [comment]
Is the client really logged in?

You can enable SDK logs and check what is happening.

**Comment by EdZava** [comment]
If it was a problem in the initialization of the twillio SDK api client that never initialized correctly, but did not give any error message when opening the application.

I have modified and made some contructions to the project to fix this problem and other bugs in the project.

This is the pull request with the changes:
#119
