### ISSUE TITLE
@twilio/conversations postinstall script fails to run

### ISSUE THREAD

**Issue by orzechowskid** [twilio/twilio-conversations-demo-react#12]
while installing `@twilio/conversations@^2.0.0`, I get this error during the postinstall step with yarn 3 on Ubuntu:

```
➤ YN0009: │ @twilio/conversations@npm:2.0.0 couldn't be built successfully (exit code 127, logs can be found here: /tmp/xfs-a48fafed/build.log)
```
that file contains the following:
```
# This file contains the result of Yarn building a package (@twilio/conversations@npm:2.0.0)
# Script name: postinstall

command not found: if
command not found: then
command not found: fi
```
a comment [here](https://github.com/twilio/twilio-conversations-demo-react/issues/4#issuecomment-988311458) seemed to imply that a fix would be coming, but AFAICT there have been no releases of `@twilio/conversations` since the original 2.0.0 a few months ago.

are there any workarounds I can try in the meantime?

thanks!

**Comment by InfiniteRain** [comment]
Hello, the fix for that is coming in the upcoming release. Before then, you could install it via Yarn/NPM via flag that disables postinstall script. On yarn it is `--ignore-scripts`.

**Comment by orzechowskid** [comment]
I believe `yarn install --ignore-scripts` will ignore _all_ postinstall scripts, not just the one for this package.

**Comment by InfiniteRain** [comment]
We are aware of the issue, the real fix will be released in the next couple of days.

**Comment by InfiniteRain** [comment]
@orzechowskid 
This issue has now been resolved in https://github.com/twilio/twilio-conversations-demo-react/pull/13.
