### ISSUE TITLE
Conversations list in the left pane is not scrollable

### ISSUE THREAD

**Issue by jmozzart** [twilio/twilio-conversations-demo-react#129]
Also it will be also nice to make it searchable.

**Comment by jmozzart** [comment]
Thank you very much @lesquive . This feature is really useful.

**Comment by jmozzart** [comment]
Also, I'm just curious, what if the conversations are more than a hundred in the record. How this app handles that kind of long list?

**Comment by lesquive** [comment]
I haven't had the opportunity to explore this just yet, but I'll certainly revisit this thread to provide an answer once I've had the chance to experiment with it in the future.

**Comment by jmozzart** [comment]
I confirmed that it dont handle it well. I'm gonna open another thread for this. But the original issue was solved.
