### ISSUE TITLE
Project README instructions typo

### ISSUE THREAD

**Issue by Collin-St** [twilio/twilio-conversations-demo-react#18]
The project README [instructs to create a `firebase_config.js` file](https://github.com/twilio/twilio-conversations-demo-react#save-firebase-project-configuration-to-firebase_configjs-file-in-the-public-folder), while the app is is designed to [import `firebase-config.js`](https://github.com/twilio/twilio-conversations-demo-react/blob/76f1d05b6796a4a7666f2260afa43698d9531b3e/public/firebase-messaging-sw.js#L5).

**Comment by berkus** [comment]
Fixed!
