### ISSUE TITLE
If the user is not connected to the web initially, he will not receive the messages the first time

### ISSUE THREAD

**Issue by fernandosngular** [twilio/twilio-conversations-demo-react#28]
I am experiencing some strange behavior:
If I send a message to a new conversation, where there is a person who is not logged in in this demo... when that person enters the page they will not see any of the sent messages.

Only when either of the two people send a new message will it work normally.

I think it may be because there is some kind of listener or behavior that is not initialized correctly.

Have you ever been to a similar situation? How can I solve that?

Thank you

**Comment by Gray-Wind** [comment]
Hello,

Please create [a support ticket](http://twilio.com/console/support/tickets/create) and attach [logs](https://www.twilio.com/docs/conversations/error-handling-diagnostics#javascript-logging) from the SDK to that ticket.

**Comment by berkus** [comment]
Closing as incoming support ticket would be used to track it.
