### ISSUE TITLE
Redux make this demo hard to read 

### ISSUE THREAD

**Issue by bymoe** [twilio/twilio-conversations-demo-react#30]
Just saying.

I don't think using an over-engineering tool like Redux is a good idea for "demo" apps,
I noticed that I been battling with navigating between Redux reducers and actions just to get to know how basic things work in this SDK

**Comment by berkus** [comment]
@bymoe hi, we are working on an improvement in this area to remove some unnecessary jumping around, hopefully it will make redux-based demo app less annoying to try.

However, using Twilio SDK with Redux or similar stores is often a pain point for developers and we wanted to show how to do it properly in the demo app itself.
