### ISSUE TITLE
What is the username & password to be used to login to twilio conversation demo app

### ISSUE THREAD

**Issue by suhasdevegowda** [twilio/twilio-conversations-demo-react#33]
What is the username & password to be used to login to twilio conversation demo app.
<img width="1792" alt="Screenshot 2022-08-30 at 5 58 49 PM" src="https://user-images.githubusercontent.com/86056296/187436782-82c4d490-be73-42af-8450-0f9862ca4d07.png">

**Comment by berkus** [comment]
It is whatever you set it to [in here](https://github.com/twilio/twilio-conversations-demo-react#for-testing-purposes-it-is-possible-to-create-a-simple-token-generator-using-a-twilio-function).

**Comment by darde** [comment]
Sorry, it is not clear for me where to set the credentials. I've already created an `.env` file with the token function

**.env**
```
REACT_APP_ACCESS_TOKEN_SERVICE_URL=https://twilio-react-chat-service-01234.twil.io/token-service
```
However, on the docs, this is the instruction. I can't understand where I should put this query string, and where I set up the credentials.
```
$REACT_APP_ACCESS_TOKEN_SERVICE_URL?identity=<USER_PROVIDED_USERNAME>&password=<USER_PROVIDED_PASSWORD>
```

Can you please clarify?

**Comment by darde** [comment]
> It is whatever you set it to [in here](https://github.com/twilio/twilio-conversations-demo-react#for-testing-purposes-it-is-possible-to-create-a-simple-token-generator-using-a-twilio-function).

Sorry, it is not clear for me where to set the credentials. I've already created an `.env` file with the token function

**.env**
```
REACT_APP_ACCESS_TOKEN_SERVICE_URL=https://twilio-react-chat-service-01234.twil.io/token-service
```
However, on the docs, this is the instruction. I can't understand where I should put this query string, and where I set up the credentials.
```
$REACT_APP_ACCESS_TOKEN_SERVICE_URL?identity=<USER_PROVIDED_USERNAME>&password=<USER_PROVIDED_PASSWORD>
```

Can you please clarify?

**Comment by berkus** [comment]
@darde the token generator provides tokens based on your credentials, so the token generator function decides what users and passwords are. In the demo they are set in the generator function - https://github.com/twilio/twilio-conversations-demo-react#generating-access-tokens-with-twilio-functions

There's a section which lists users and passwords for testing:

```
// If you do not want to pay for other people using your Twilio service for their benefit,
// generate user and password pairs different from what is presented here
let users = {
    user00: "", !!! SET NON-EMPTY PASSWORD AND REMOVE THIS NOTE, THIS GENERATOR WILL NOT WORK WITH EMPTY PASSWORD !!!
    user01: ""  !!! SET NON-EMPTY PASSWORD AND REMOVE THIS NOTE, THIS GENERATOR WILL NOT WORK WITH EMPTY PASSWORD !!!
};
```
