### ISSUE TITLE
setLastReadIndex and consumed messages

### ISSUE THREAD

**Issue by fernandosngular** [twilio/twilio-conversations-demo-react#34]
I'm having trouble displaying unread messages correctly.

For example, if the user is not inside the web demo and a new conversation is created, when said user enters the web demo he does not see the notifications (those that appear on the left), correctly.

Maybe it's related to firebase notifications that I have them turned off?

Thank you

**Comment by berkus** [comment]
There are some fixes pending regarding this in the main branch, they would be merged shortly.

If you're curious, look in the `fix/swarm` branch.

**Comment by fernandosngular** [comment]
Last fix work, thanks
