### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by colaquecez** [twilio/twilio-conversations-demo-react#38]
We have a project in React Native, can we use the JS REACT SDK, or do I need to create bridges for Swift and Java?

**Comment by berkus** [comment]
You can use pure JS SDK, there's no JS REACT SDK, but you will need to bridge a couple of things - namely ios and android push notifications infra. There are some packages in React Native ecosystem that handle this, afaik.

@Gray-Wind could tell me from this experience setting it up.

**Comment by colaquecez** [comment]
I see, but for the message, audio and video calls, I can use just the JS SDK, right?
