### ISSUE TITLE
error Command failed with exit code 127.

### ISSUE THREAD

**Issue by twilio-akiramoto** [twilio/twilio-conversations-demo-react#4]
Hello team, 
I am deploying this repo and I am getting:

yarn build

yarn run v1.21.1
$ react-scripts build
/bin/sh: react-scripts: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

How can I fix this?

Thanks!

**Comment by MonstraG** [comment]
> 
> 
> found the issue, pls disregard

Have it to installing ` @twilio/conversations`, what was it?

**Comment by twilio-akiramoto** [comment]
@MonstraG - that was it, proper install yarn fixed my issue. Thank you for following up!

**Comment by MonstraG** [comment]
Hm, it still fails to build for me with this:
```
# This file contains the result of Yarn building a package (@twilio/conversations@npm:2.0.0)
# Script name: postinstall

"-f" was unexpected at this time.
command not found: if
'then' is not recognized as an internal or external command,
operable program or batch file.
command not found: then
'fi' is not recognized as an internal or external command,
operable program or batch file.
command not found: fi
```

**Comment by berkus** [comment]
The postinstall script thingie fix should be released shortly.
