### ISSUE TITLE
WebSocket SyncError: disconnected (status: 0, code: 0)

### ISSUE THREAD

**Issue by ababu-speedum** [twilio/twilio-conversations-demo-react#41]
Some Time i get this error and my ui gets frezzzy or slow to load the chats

**Comment by berkus** [comment]
You're losing your internet connection it seems?

**Comment by ababu-speedum** [comment]
![image](https://user-images.githubusercontent.com/99633223/195592829-873540ba-b628-424a-b999-afeab8352c0d.png)

**Comment by berkus** [comment]
Yeah, the _speed_ has nothing to do with disconnections. Only the stability and latency of the connections to US servers.

**Comment by ababu-speedum** [comment]
twilio conversations client internal binding method does causes frizziness to ui ? because some time i am facing it while sending message and loading messages.

**Comment by berkus** [comment]
Sending and loading messages needs to communicate with the backend.

Can you record a video of what you mean by "frizziness"?

**Comment by ababu-speedum** [comment]
its network issue.
