### ISSUE TITLE
How to delete the chats for the participant who has left the conversation 

### ISSUE THREAD

**Issue by ababu-speedum** [twilio/twilio-conversations-demo-react#44]
How to delete the chats for the participant who has left the conversation. The other participants could still see the message of the left ones.

**Comment by berkus** [comment]
Delete the chats? Delete the messages?

**Comment by ababu-speedum** [comment]
delete chats

**Comment by ababu-speedum** [comment]
If you and I are in conversation, When I left the conversation and you still message me which will add me before sending the message then I will only start seeing the message that you have sent not all the old chats with it.

**Comment by ababu-speedum** [comment]
While leaving the conversation I want to delete the chats before leaving. Or I can do that is to updating the attributes of the conversation and saving the last message index, when I again join it the start showing the message from that index. ?

**Comment by ababu-speedum** [comment]
when I leave the conversation then delete the chats of my side before leaving. That's what I want

**Comment by berkus** [comment]
Then you need to find all your meaaages in the conversation and delete them, if i understood you correctly. You can perform it with a backend webhook i believe.

**Comment by ababu-speedum** [comment]
Do I have to go through each message?

**Comment by berkus** [comment]
Yes, there's no way to automatically delete participant's messages when he leaves.

**Comment by ababu-speedum** [comment]
ok, thanks. I have one more question regarding TTL of the access token. I want to increase the token expiration time

![image](https://user-images.githubusercontent.com/99633223/200530096-4c3f882c-df88-41aa-8b8f-a276aafb3b3e.png)

**Comment by ababu-speedum** [comment]
Like this ?
![image](https://user-images.githubusercontent.com/99633223/200542797-c88c8d5f-5941-4991-a984-dd0fbf105ec4.png)

**Comment by berkus** [comment]
This demo app has [an example](https://github.com/twilio/twilio-conversations-demo-react/blob/ffc60f193b301b44fe7859ab926c4291b0c621e4/src/components/AppContainer.tsx#L227).

**Comment by ababu-speedum** [comment]
it still loses the connection. or when I send a new message it creates multiple copies.

in the useEffect I am using

   return () => {
      client?.removeAllListeners();
      setClient("")
    };
