### ISSUE TITLE
Destroy client at logout 

### ISSUE THREAD

**Issue by ababu-speedum** [twilio/twilio-conversations-demo-react#46]
How to destroy the client at logout.
when log in again then it creates a duplicate of the message while  adding 

this listener runs two times
  client.on("messageAdded", (event) => {
        console.log("messageAdded")})

**Comment by berkus** [comment]
On logout, [this piece](https://github.com/twilio/twilio-conversations-demo-react/blob/main/src/components/AppContainer.tsx#L236-L238) should be run which drops all listeners.
