### ISSUE TITLE
how to check user is online

### ISSUE THREAD

**Issue by ababu-speedum** [twilio/twilio-conversations-demo-react#47]
I have checked this post.
https://stackoverflow.com/questions/72098884/twilio-conversations-get-online-users

after setting the reachability to true 
![image](https://user-images.githubusercontent.com/99633223/200822776-66feb569-24cf-43b0-8854-fce2fe124fa2.png)

how I will get the online status value from the participants 

const participants = await conversation.getParticipants()

participants.forEach(v=>{
console.log(v.getUser().isOnline)
})

in console getting undefined

**Comment by berkus** [comment]
getUser() returns a promise.

**Comment by ababu-speedum** [comment]
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ababu-speedum** [comment]
how to get value in real-time? 
it only updates when I navigate between the conversation list and the current conversation.

**Comment by Gray-Wind** [comment]
Hello, it solely depends on your implementation.

**Comment by ababu-speedum** [comment]
I am getting the user's online status, What I want is to get the offline status of the user as soon user logout.

Suppose there are two users, Both are in a conversation, and user1 chats with user2, which is currently online right now, as soon as user2 goes offline 
how I can show the offline status of user2 to user1?
Are there any event listeners?

**Comment by berkus** [comment]
You will get [User.updated](https://sdk.twilio.com/js/conversations/releases/2.2.0/docs/classes/User.html#updated) event with "reachabilityOnline" reason and you can check the new reachability there.

**Comment by ababu-speedum** [comment]
Like this?

      const chatClient = new Client(token);
      const user = chatClient.user
      user.on('updated', function (event) {
        console.log(event, "event")
      });
      
      
      but this is for the current user, I am not able to see this event triggered to other users when current user logout
      i have shutdown the chatClient in useEffect return function
      
      
    return () => {
      chatClient?.removeAllListeners();
      chatClient?.shutdown()
    };

**Comment by berkus** [comment]
Subscribe to other users' events to receive updates for them. You cannot receive reachability events for yourself, obviously.

**Comment by ababu-speedum** [comment]
I am not getting updateReasons "online"

![image](https://user-images.githubusercontent.com/99633223/203016439-0e3eac75-1f77-4e4e-8896-9c672679db7c.png)

getting this when login 
![image](https://user-images.githubusercontent.com/99633223/203016656-3bb1dd93-4664-4098-b1c2-35dcff2deb6e.png)

I have used this

    client.conversations.v1
      .services(config?.chatServiceSid)
      .configuration()
      .update({ reachabilityEnabled: true,isOnline: true})

**Comment by berkus** [comment]
True, list of update reasons does not include "online", see the docs.

**Comment by ababu-speedum** [comment]
How I will get the other users list using client?

**Comment by ababu-speedum** [comment]
I have shutdown the client and the connection state goes to disconnect but in the event userUpdated isOnline is still true.

![image](https://user-images.githubusercontent.com/99633223/203226494-3de2683d-a69c-45de-a324-c16388df8213.png)

**Comment by ababu-speedum** [comment]
![image](https://user-images.githubusercontent.com/99633223/203270780-547b1e46-c30b-4931-9829-4ca5366328f0.png)

I want to turn the green to gray color as soon as the user goes offline.

**Comment by ababu-speedum** [comment]
Got it Thanks !!!
 chatClient.on("userUpdated", ({ user, updateReasons }) => {
        if (updateReasons.includes("reachabilityOnline")) {
          if (user?.isOnline) {
            setActiveUsers(prev => [...prev, user])
          }
          if (!user?.isOnline) {
            setActiveUsers(prev => prev?.filter(u => u?.identity !== user?.identity))
          }
        }
      });

**Comment by berkus** [comment]
Unfortunately this is not a support forum. Please consult the SDK docs and raise a Twilio Support ticket if necessary.
