### ISSUE TITLE
CONVERSATIONCLIENT.getSubscribedConversation doesn't update instantly

### ISSUE THREAD

**Issue by furqansays** [twilio/twilio-conversations-demo-react#66]
**When a user leaves a conversation, the CONVERSATIONCLIENT.getSubscribedConversation method still shows that chat.**

**Comment by rusmonster** [comment]
Could you provide logs where this issue is reproduced please?

**Comment by RicardoNunoAlmeida** [comment]
@furqansays  - can you please provide the logs requested by @rusmonster? Thank you!

**Comment by RicardoNunoAlmeida** [comment]
Closing giving lack of input from user. Thank you, and please open a new ticket in case you get back to this @furqansays!
