### ISSUE TITLE
Getting Error on Chat Participant add

### ISSUE THREAD

**Issue by noorarman** [twilio/twilio-conversations-demo-react#69]
Hello, i cloned the repo and setup the dependencies and everything on twilio console.
I'm getting an error when I try to add a Chat Participant to a conversation.
I dunno what I m doing wrong. 
I've logged the error to the console.
```
if (chatParticipant && name.length > 0) {
    try {
      const result = await convo.add(name);
      successNotification({
        message: PARTICIPANT_MESSAGES.ADDED,
        addNotifications,
      });
      return result;
    } catch (e) {
      console.log(e);
      return Promise.reject(e);
    }
  }}

```
Here is the picture:
![Twilio](https://user-images.githubusercontent.com/56154485/215986336-3f563430-743d-4738-9489-2bf6741d30f8.png)

**Comment by InfiniteRain** [comment]
Did you give appropriate permissions for channel user/channel admin roles? You need the addParticipant permission to add a participant and removeParticipant permission to remove one.

**Comment by noorarman** [comment]
> Did you give appropriate permissions for channel user/channel admin roles? You need the addParticipant permission to add a participant and removeParticipant permission to remove one.

@InfiniteRain thank you for the support. Well instead of serverless twilio function to generate token i m generating tokens on node.js server. I've couple of services e.g `admin`, `client`, `vendor` and `candidate` the default service is admin. My question is how to tell node.js SDK that 

```
const accountSid = process.env.TWILIO_ACCOUNT_SID;
const authToken = process.env.TWILIO_AUTH_TOKEN;
const client = require('twilio')(accountSid, authToken);

client.conversations.v1.users
                       .create({identity: 'RedgrenGrumbholdt'})
                       .then(user => console.log(user.sid));
```
perform this operation for `client` service instead of the default(`admin`) service?

**Comment by Gray-Wind** [comment]
Hello @noorarman,

In the given sample you create a user with a name `RedgrenGrumbholdt`.
Basically you need to set up permission for [the different roles](https://www.twilio.com/docs/conversations/api/role-resource) in the [Console](https://console.twilio.com/). The [permission](https://www.twilio.com/docs/conversations/api/role-resource#permission-values) you are looking for is called `addParticipant`. You can set this permission either service wide, or conversation wide.

**Comment by noorarman** [comment]
@Gray-Wind thanks for the support.
